app_identifier "ch.architectdna.noor"
username "systems@architect-dna.ch"

name({ "en-US" => "NOOR — Dhikr & Reflection" })
subtitle({ "en-US" => "Daily Islamic Remembrance" })


primary_category "LIFESTYLE"
secondary_category "HEALTH_AND_FITNESS"


copyright "© 2026 Muharrem Akdemir"

automatic_release false

submit_for_review false  # set true when ready to submit

metadata_path "./fastlane/metadata"
screenshots_path "./fastlane/screenshots"

skip_screenshots false
skip_metadata false

languages ["en-US"]
